baseURL = "https://praxis.nyc"
languageCode = "en-us"
title = "Praxis"
description = "Decolonize your attention test"
logo = "logo-big.svg"
category = ["study", "commons", "play"]
include = [".well-known"]
publishDir = "docs"
